produto1 = input(("Digite o nome do produto 1: "))
preco1 = float(input("Digite o preço unitário do produto 1: "))
quant_prod1 = int(input("Digite a quantidade do produto 1: "))
produto2 = (input("Digite o nome do produto 2: "))
preco2 = float(input("Digite o preço unitário do produto 2: "))
quant_prod2 = int(input("Digite a quantidade do produto 2: "))
produto3 = (input("Digite o nome do produto 3: "))
preco3 = float(input("Digite o preço unitário do produto 3: "))
quant_prod3 = int(input("Digite a quantidade do produto 3: "))
total = (preco1 * quant_prod1 + preco2 * quant_prod2 + preco3 * quant_prod3)
print(f"Total: R${total:,.2f}")